services:
  docs:
    image: essa_construction_local_docs
    container_name: essa_construction_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./essa_construction:/app/essa_construction:z
    ports:
      - '9000:9000'
    command: /start-docs
